spring:  
  application:  
    name: EUREKA-HA  
---  
server:  
  port: 8888  

eureka:  
  instance:  
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: false  
    serviceUrl:  
      defaultZone: http://localhost:8888/eureka/  

 
